<!DOCTYPE html>
<html lang="en">

<head>
  <title>... Summary</title>
  <meta charset="utf-8">
  <link href="../css/basic-layout.css" type="text/css" rel="stylesheet"/>
  <link href="../css/summary-page-layout.css" type="text/css" rel="stylesheet"/>
  <link id="summary-page-layout" href="../css/normal-text-summary-page.css" type="text/css" rel="stylesheet"/>
</head>

<body>

  <div id="header-container">

        <h1 id="main-header">Helpful ...</h1>

        <div id="contents-container">
          <div class="header-divider divider"></div>
          <table id="search-and-sort-table">
            <tr>
              <td>
                <form name="search-form">
                  <input id="contents-search-box" class="section-text-normal" type="text" name="search-term"/>
                </form>
              </td>
              <td>
                <p id="search-button" class="section-text-normal">
                  <span class="vertical-align-text">Search</span>
                </p>
              </td>
              <td>
                <p id="order-button" class="section-text-normal">
                  <span class="vertical-align-text"></span>
                </p>
              </td>
            </tr>
          </table>

        </div>
        <div class="header-divider divider"></div>
  </div>

  <div id="header-space"></div>

  <div id="primary-container">

    <div class="divider"></div>

    <div class="section">

      <div class="title-anchor"></div>
      <h2 class="section-header">Exceptions and Error Handling</h2>

      <div class="section-content section-text-normal">
        <p>
          Exception allow code to manage uncontrollable situations and coding
          mistakes effectivly. When an exception arises the normal flow is
          disrupted and the program will exit abnormally.
        </p>

        <p>
          In Java the class Throwable is the superclass for all classes which
          are involved in error management. The three main subclasses of
          Throwable are Error, Exception and RuntimeException.
        </p>

        <p>
          <b>Error</b> is used in situations in which a program should not
          recover from. They are abnormal conditions that are not commonly
          encountered and are beyond the programmers control.<br>
          <b>Exception</b> (also known as checked exceptions) and its subclasses
          (except for RuntimeException and its subclasses) are used for
          anticipated issues which a program could recover from. These occure at
          compile time and must be handled by the programmer.<br>
          <b>RuntimeException</b> (also known as unchecked exceptions) and its
          subclasses are used in general situations such as the array index
          being out of bounds.<br>
        </p>

        <img
          src="../examples/java/exception_basic_hierarchy.png"
          alt="A outline of the Java exception hierarchy">

        <h3>Common runtime / unchecked exceptions</h3>
        <ul>
            <li><b>ArrayIndexOutOfBoundsException</b>: Array index is out-of-bounds.</li>
            <li><b>ClassCastException</b>: Invalid cast.</li>
            <li><b>IllegalArgumentException</b>: Illegal argument used to invoke a method.</li>
            <li><b>IndexOutOfBoundsException</b>: Some type of index is out-of-bounds.</li>
            <li><b>NullPointerException</b>: Invalid use of a null reference.</li>
            <li><b>NumberFormatException</b>: Invalid conversion of a string to a numeric format.</li>
            <li><b>UnsupportedOperationException</b>: An unsupported operation was encountered.</li>
        </ul>

        <h3>Common Checked exceptions</h3>
        <ul>
            <li>
              <b>IOException</b>: Thrown due to issues with reading or writting
              files.
            </li>
            <li><b>ClassNotFoundException</b>: Class not found.</li>
            <li><b>DataFormatException</b>: Class not found.</li>
            <li><b>NoSuchMethodException</b>: Class not found.</li>
        </ul>

        <p>
          <a href="../examples/java/exception_list.txt">List of exceptions 1 provided by <b>Hai Vu</b></a><br>
          <a href="https://bitbucket.org/htv2013/java-exception-list/src/9e839f0cf062795a56a05679cbb03ee7954158d8/exceptions.txt?at=master&fileviewer=file-view-default">
            View list 1 online.
          </a>
        </p>
        <p>
          <a href="../examples/java/exception_list_2.txt">List of exceptions 2 (including hieracy) provided by <b>Carnegie Mellon University</b></a><br>
          <a href="https://www.cs.cmu.edu/~pattis/15-1XX/15-200/lectures/exceptions/lecture.html">
            View list 2 online.
          </a>
        </p>

        <h3>Try - Catch - Finally</h3>
        <p>
          In order to handle checked or unchecked exceptions try, catch, finally
          blocks are used to surround sections of code which may cause errors.
          The try surrounds the code that could throw an exception and the catch
          block defines which exception to look for and how to manage it. The
          finally block is optional and provide a place to write code which
          should always run after the try catch blocks regardless of wether an
          exception was thrown. This is useful in situation such as closing
          databases. It can be used to esure close is called on the database
          object even if the connection fails.
        </p>

        <p>
          Try catch blocks must surround any code which throws checked exceptions
          but unchecked exception are optional.
        </p>

        <p>
          <b>
            public class Main{<br>
            <br>
            &#160;&#160;public static void main(String[] args) {<br>
            &#160;&#160;&#160;&#160;try{<br>
            &#160;&#160;&#160;&#160;&#160;&#160;int i = 1 / 0;<br>
            &#160;&#160;&#160;&#160;}catch(Exception ex){<br>
            &#160;&#160;&#160;&#160;&#160;&#160;System.out.println(ex.getMessage());<br>
            &#160;&#160;&#160;&#160;}finally{<br>
            &#160;&#160;&#160;&#160;&#160;&#160;System.out.println("Finally I do something");<br>
            &#160;&#160;&#160;&#160;}<br>
            &#160;&#160;}<br>
            }
          </b>
        </p>

        <p>
          The exception defined by the catch block can be any of the previouly
          mentioned. The block will catch the named exception and all its child
          exceptions. So if Exception is named by the catch block all exceptions
          will be caught. Specific exception use is prefered however and to allow
          this multiple catch blocks may be defined.
        </p>

        <p>
          <b>
            public class Main{<br>
            <br>
            &#160;&#160;public static void main(String[] args) {<br>
            &#160;&#160;&#160;&#160;try{<br>
            &#160;&#160;&#160;&#160;&#160;&#160;int i = 1 / 0;<br>
            &#160;&#160;&#160;&#160;}catch(ArithmeticException ex){<br>
            &#160;&#160;&#160;&#160;&#160;&#160;System.out.println(ex.getMessage());<br>
            &#160;&#160;&#160;&#160;}catch(IllegalArgumentException ex){<br>
            &#160;&#160;&#160;&#160;&#160;&#160;System.out.println(ex.getMessage());<br>
            &#160;&#160;&#160;&#160;}finally{<br>
            &#160;&#160;&#160;&#160;&#160;&#160;System.out.println("Finally I do something");<br>
            &#160;&#160;&#160;&#160;}<br>
            &#160;&#160;}<br>
            }
          </b>
        </p>

        <p>
          To throw exceptions based on a personal condition the keyword throw is
          used. In the case of checked exceptions as long as a try catch block
          surrounds a method which ultimatly lead to the thrown exception the
          code will compile.
        </p>

        <p>
          <b>
            if(true){<br>
            &#160;&#160;throw new IllegalArgumentException("Error message");<br>
            }
          </b>
        </p>

        <p>
          methods which throw exceptions (need more than book).
          extending methods which throw exceptions, cannot declare new exceptions
          but can declare less
        </p>

        <p>
          (Sources:<br>
          <a href="https://www.tutorialspoint.com/java/java_exceptions.htm">
            Tutorials Point: Java - Exceptions
          </a><br>
          <a href="https://www.tutorialspoint.com/java/java_builtin_exceptions.htm">
            Tutorials Point: Built in exceptions
          </a><br>
          <a href="https://bitbucket.org/htv2013/java-exception-list/src/9e839f0cf062795a56a05679cbb03ee7954158d8/exceptions.txt?at=master&fileviewer=file-view-default">
            Hai Vu's BitBucket: Java Exception List
          </a><br>
          <a href="https://www.cs.cmu.edu/~pattis/15-1XX/15-200/lectures/exceptions/lecture.html">
            Carnegie Mellon University: Exceptions in Detail
          </a>)
        </p>
        <p><em>Updated:</em></p>
      </div>

    </div>

    <div class="divider"></div>

  </div>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" rel="javascript"></script>
  <script src="../j-script/contents-arrays/contents-item.js" rel="javascript"></script>
  <script src="../j-script/contents-arrays/ruby-contents.js" rel="javascript"></script>
  <script src="../j-script/manage-contents.js" rel="javascript"></script>
  <script src="../j-script/contents-arrays/contents-search.js" rel="javascript"></script>
  <script src="../j-script/header.js" rel="javascript"></script>
  <script src="../j-script/summary-layout-switcher.js" rel="javascript"></script>
  <script src="../j-script/summary-pages-events.js" rel="javascript"></script>

</body>

</html>
